# app/models.py

# Import column types (Integer, String, Float) and the Column class from SQLAlchemy
from sqlalchemy import Column, Integer, String, Float

# Import the 'Base' class we created in 'database.py'
from .database import Base

# Define the 'AnalysisReport' class inheriting from 'Base'.
# This tells SQLAlchemy that this class corresponds to a database table.
class AnalysisReport(Base):
    
    # Specify the name of the table in the database.
    __tablename__ = "analysis_reports"

    # --- Define the table columns ---
    
    # id: A unique identifier number for each report; it increments automatically.
    # primary_key=True: Marks this column as the primary key (unique for every row).
    # index=True: Creates an index for this column to make search queries faster.
    id = Column(Integer, primary_key=True, index=True)

    # text_to_analyze: Stores the text input provided by the user for analysis.
    text_to_analyze = Column(String)

    # novelty_score: Stores the calculated novelty score (a decimal number).
    novelty_score = Column(Float)

    # summary: Stores the text summary generated by the analysis.
    summary = Column(String)